SimpleBlogPlatformProject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("user/", include("user.urls")),
]

main/urls.py
from django.urls import include, path

from main import views

app_name = "main"

urlpatterns = [
    path("main/", views.main_view, name="main_view"),
    path("search/", views.search_view, name="search"),
]

user/urls.py
from django.urls import include, path

from user import views

app_name = "user"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("signup/", views.registration, name="signup"),
    path("profile/", views.user_profile, name="profile"),
]

main/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models

from user.models import User

# Create your models here.


class Post(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=100, blank=True, null=True)
    image = models.ImageField(upload_to="post/images/", null=True, blank=True)
    hidden = models.BooleanField(default=False)
    likes = models.IntegerField(default=0)
    comments = models.IntegerField(default=0)
    favorites = models.IntegerField(default=0)
    reposts = models.IntegerField(default=0)

user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.


class User(AbstractUser):
    first_name = models.CharField(max_length=35)
    last_name = models.CharField(max_length=35)
    username = models.CharField(max_length=35, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    image = models.ImageField(upload_to="user/images/", null=True, blank=True)
    coins = models.PositiveIntegerField(default=10)
    is_blocked = models.BooleanField(default=False)
    subscribers = models.ManyToManyField(
        "self",
        related_name="subscriptions",
        symmetrical=False,
        through="UserSubscribers",
    )

    class Meta:
        db_table = "User"
        verbose_name = "user"
        verbose_name_plural = "users"


class UserSubscribers(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="user_subscribers"
    )
    subscriber = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="user_subscriptions"
    )

    class Meta:
        unique_together = ("user", "subscriber")


class Settings(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_see = models.BooleanField(default=True)


class TransactionsLog(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    transaction = models.CharField(max_length=100)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True, null=True, max_length=500)

user/forms.py
from string import ascii_letters, digits

from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator
from django.db.models import Q
from django.utils.deconstruct import deconstructible

from .models import User


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={"class": "LoginInput"}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"class": "PasswInput"})
    )

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get("username")
        password = cleaned_data.get("password")

        user_obj = User.objects.filter(Q(username=username) | Q(email=username)).first()
        if not user_obj:
            raise ValidationError("Невірне ім'я або пароль")
        user = authenticate(username=user_obj.username, password=password)
        if not user:
            raise ValidationError("Невірне ім'я або пароль")
        if user.is_blocked:
            raise ValidationError("Ваш обліковий запис заблоковано.")

        return cleaned_data

    def get_user(self):
        return getattr(self, "user_cache", None)


class RegistrationForm(forms.ModelForm):

    password1 = forms.CharField(
        max_length=30, widget=forms.PasswordInput(attrs={"class": "PasswordInp"})
    )
    password2 = forms.CharField(
        max_length=30, widget=forms.PasswordInput(attrs={"class": "PasswordInp"})
    )

    class Meta:
        model = User
        fields = (
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
            "password",
        )

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get("username")
        email = cleaned_data.get("email")
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")

        if password1 != password2:
            raise ValidationError("Паролі не співпадають.")

        if User.objects.filter(username=username).exists():
            self.add_error(
                "username",
                "Даний нікнейм користувача вже існує! Придумайте інший нікнейм.",
            )

        if User.objects.filter(email=email).exists():
            self.add_error(
                "email",
                "На дану електронну пошту вже зареєстровано акаунт! Введіть іншу.",
            )

        if not set(username).issubset(set(ascii_letters + digits)):
            self.add_error(
                "username",
                "У полі нікнейм дозволені лише латинські літери та цифри.",
            )

        return cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

main/views.py
from django.shortcuts import render

from user.models import User
from utils.search_func import q_search


def main_view(request):
    return render(request, "main_page/main.html")


def search_view(request):
    query = request.GET.get("q")
    if query:
        search_result = q_search(query)
    else:
        search_result = User.objects.all()
    return render(
        request, "search_results/search_result.html", {"search_result": search_result}
    )

posts/views.py
from django.shortcuts import render

# Create your views here.

user/views.py
import os

from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.decorators.http import require_http_methods

from .forms import LoginForm, RegistrationForm
from .models import User


def login(request):
    form = LoginForm()
    if request.method == "POST":
        form = LoginForm(data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect("main:main_view")
    return render(request, "login_template/login.html", {"form": form})


def registration(request):
    if request.method == "POST":
        form = RegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("user:login")
    else:
        form = RegistrationForm()
    return render(request, "singUpTemplate/singup.html", {"form": form})


def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect("main:main_view")


def image_url(instance, filename):
    dir_name = (
        f"{instance.first_name[0]}_{instance.last_name[0]}_{instance.username[0]}"
    )
    return f"user/images/{dir_name}/{filename}"


def user_profile(request):
    return render(request, "profile_template/profile.html")

main/templates/main_page/main.html
{% extends 'base.html' %}
{%  block header %}{% include 'includes/header.html' %}{%  endblock %}

main/templates/search_results/search_result.html
{% extends 'base.html' %}
{% load static %}
{% block links %}<link type="text/css" rel="stylesheet" href="{% static 'search_page/search_page.css' %}">{% endblock %}
{%  block header %}{% include 'includes/header.html' %}{%  endblock %}
{% block content %}
    <div class="main_search_div">
        {% for res in search_result %}
            <div class="res_card">
                <div class="img_div">
                    {% if res.image %}
                    <img class="res_img" src="{{ res.image }}" id="img">
                {% else %}
                    <img class="res_img" src="{% static 'user_image/user_image.png' %}">
                {% endif %}
                </div>

                <div class="inf_div">

                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/base.html
{% load static %}
<html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link type="text/css" href="{% static 'base.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
    {% block links %}{% endblock %}
</head>
<body>
{%  block header %}{% endblock %}
{% block content %}{% endblock %}
</body>
</html>

templates/includes/header.html
{% load static %}
{% block header %}
    <div class="header">
        <nav class="main_nav">
            <div class="LogoContainer" onclick="window.location.href='{% url  'main:main_view' %}'">
                <img src="{% static 'logo/KuMessageLogo.png'%}" alt="KuMessageLogo" class="LogoImg">
                <p class="LogoName" >KuMessage</p>
            </div>
        </nav>
        <nav class="main_nav buttons_nav">
            {% if not user.is_authenticated %}
            <button class="loginButton" onclick="window.location.href='{% url 'user:login' %}'">Login</button>
            {% else %}
                <a onclick="window.location.href='{% url 'user:profile' %}'"><p class="username_main"><i class='bx  bx-user'  style='color:#000000'></i>{{ user.username }}</p></a>

                <form class="form_search" method="get" action="{% url 'main:search' %}">
                    <div class="form_search_div">
                        <input class="search_input" type="text" placeholder="Search" name="q" aria-label="Search">
                        <button class="search_button" style="margin: 20px" type="submit">Пошук</button>
                    </div>
                </form>

                <button class="loginButton" onclick="window.location.href='{% url 'user:login' %}'">Logout</button>
            {% endif %}
        </nav>
    </div>
    <div class="line"></div>
{% endblock %}

user/templates/login_template/login.html
{% extends 'base.html' %}
{% load static %}
{%  block links %}
    <link type="text/css" rel="stylesheet" href="{% static 'login_page/login.css' %}">
{% endblock %}
{% block content %}
<div class="login_page_container">
    <img src="{% static 'logo/KuMessageLogo.png' %}" class="LogoImage">
    <p class="LogoName">K</p>
    <div class="login_container">
        <div class="FormContainer">
            <form method="post">
                <div class="LoginLettersContainer">
                    <p class="LoginLetters">Login</p>
                </div>
                <div class="ButtonContainer">
                    <button class="LoginButtonF" onclick="window.location.href='{% url 'user:login' %}'">Login</button>
                    <button class="SingUpButtonF" onclick="window.location.href='{% url 'user:signup'%}'">SignUp</button>
                </div>
                {% csrf_token %}
                {% if form.non_field_errors %}
                    <div class="errorlist nonfield">
                        {% for error in form.non_field_errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
                {{ form.username.errors }}
                <label for="{{ form.username.id_for_label }}">Ім'я користувача або електронна пошта</label>
                {{ form.username }}
                {{ form.password.errors }}
                <label for="{{ form.password.id_for_label }}">Пароль</label>
                {{ form.password }}
                <button class="LoginButtonPOST" type="submit">Login</button>
                <div class="SingUpContainer">
                    <p class="SingUpText">Don't have an account? </p><a onclick="window.location.href='{% url 'user:signup' %}'" class="SingUpHref">Sign Up</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

user/templates/profile_template/profile.html
{% extends 'base.html' %}
{% load static %}
{% block links %}
    <link type="text/css" rel="stylesheet" href="{% static 'profile_page/profile.css' %}">
{% endblock %}
{% block header %}
    <div class="including_div">
    {% include 'includes/header.html' %}
    </div>
{% endblock %}
{% block content %}
<div class="main_div">
    <form>
        <div class="info_div">
            <div class="image_div">
                {% if user.image %}
                    <img class="user_img" src="{{ user.image }}" id="img">
                    <input type="file" name="image" class="file_input">
                {% else %}
                    <img class="user_img" src="{% static 'user_image/user_image.png' %}">
                    <input type="file" name="image" class="file_input">
                {% endif %}
                {% if form.image.errors %}
                    <div>{{ form.image.errors }}</div>
                {% endif %}
            </div>
            <div class="digital_div">
                <div class="name_div"><p>Ім'я</p></div>
                <div class="num_div">
                    <div class="num_div_info">
                        <p>Відстежують</p>
                        <p>25</p>
                    </div>
                    <div class=num_div_info>
                        <p>Відстежуються</p>
                        <p>72</p>
                    </div>
                    <div class=num_div_info>
                        <p>Публікації</p>
                        <p>6</p>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

user/templates/singUpTemplate/singup.html
{% extends 'base.html' %}
{% load static %}

{% block links %}
    <link type="text/css" rel="stylesheet" href="{% static 'login_page/login.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'signup_page/signup.css'%}">
{% endblock %}
{% block content %}
    <div class="login_page_container">
    <img src="{% static 'logo/KuMessageLogo.png' %}" class="LogoImage">
    <p class="LogoName">K</p>
    <div class="login_container">
        <div class="LoginLettersContainer">
            <p class="LoginLetters">SignUp</p>
        </div>
        <div class="FormContainer">
            <div class="ButtonContainer">
                <button class="LoginButtonF" onclick="window.location.href='{% url 'user:login' %}'">Login</button>
                <button class="SingUpButtonF">SignUp</button>
            </div>
            <form method="post">
                {% csrf_token %}

                {% if form.non_field_errors %}
                    <div class="errorlist nonfield">
                        {% for error in form.non_field_errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}

                <label for="username_id">Юзернейм (нікнейм)</label>
                {% if form.username.errors %}<div class="error_div">{{ form.username.errors }}</div>{% endif %}
                <input type="text" class='UsernameInp' placeholder="Username" id="username_id" name="username">

                <label for="first_name_id">Ім'я</label>
                {% if  form.first_name.errors %}<div class="error_div">{{ form.first_name.errors }}</div>{% endif %}
                <input type="text" class='FirstNameInp' placeholder="First Name" id="first_name_id" name="first_name">

                <label for="last_name_id">Прізвисько</label>
                {% if form.last_name.errors %}<div class="error_div">{{ form.last_name.errors }}</div>{% endif %}
                <input type="text" class='LastNameInp' placeholder="Last Name" id="last_name_id" name="last_name">

                <label for="email_id">Електронна пошта</label>
                {% if form.email.errors %}<div class="error_div">{{ form.email.errors }}</div>{% endif %}
                <input type="text" class='EmailInp' placeholder="Email" id="email_id" name="email">

                <label for="password1_id">Пароль</label>
                <input type="password" class='PasswordInp' placeholder="Password" id="password1_id" name="password1">

                <label for="password2_id">Підтвердіть пароль</label>
                <input type="password" class='PasswordInp' placeholder="Repeat password" id="password2_id" name="password2">

                <button class="SingUpButtonPOST" type="submit">SignUp</button>
            </form>

            <div class="SingUpContainer">
            </div>
        </div>
    </div>
</div>
{% endblock %}